/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/hello": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hello world */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Hello world */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["getHelloResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mail-login/temp-regist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** メールアドレス認証 仮登録 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description メールアドレス認証 仮アカウント登録 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["postMailAuthTempRegistRequest"];
                };
            };
            responses: {
                /** @description 確認メール送信済み */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["postMailAuthTempRegistSuccessResponse"];
                    };
                };
                /** @description パラメータ誤り */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 登録済みメールアドレスです */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mail-login/regist/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** メールアドレス認証 トークン確認 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description メールアドレス登録用トークン
                     * @example 0123456789abcdef
                     */
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 正当なトークンと確認済み */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["getMailAuthRegistSuccessResponse"];
                    };
                };
                /** @description パラメータ誤り */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description トークンが無効(期限切れ) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** メールアドレス認証 新規登録 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description メールアドレス登録用トークン
                     * @example 0123456789abcdef
                     */
                    token: string;
                };
                cookie?: never;
            };
            /** @description メールアドレス認証 新規登録 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["postMailAuthRegistRequest"];
                };
            };
            responses: {
                /** @description メールアドレス認証 新規登録完了 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["postMailAuthRegistSuccessResponse"];
                    };
                };
                /** @description パラメータ誤り */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description トークンが無効(期限切れ) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mail-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** メールアドレス認証 ログイン */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description メールアドレス認証 ログイン */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["postMailAuthLoginRequest"];
                };
            };
            responses: {
                /** @description ログイン成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["postMailAuthLoginSuccessResponse"];
                    };
                };
                /** @description パラメータ誤り */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description ログイン失敗 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mail-login/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** メールアドレス認証 パスワード変更 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description メールアドレス認証 パスワード変更 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["postMailAuthChangePasswordRequest"];
                };
            };
            responses: {
                /** @description パスワード変更成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description パラメータ誤り */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["postMailAuthChangePasswordErrorResponse"];
                    };
                };
                /** @description パスワード間違い */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["postMailAuthChangePasswordErrorResponse"];
                    };
                };
                /** @description ユーザーが存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["postMailAuthChangePasswordErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mail-login/forget-password-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** メールアドレス認証 パスワード忘れた場合の URL 発行 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["postMailAuthForgetPasswordUrlRequest"];
                };
            };
            responses: {
                /** @description URL 発行成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["postMailAuthForgetPasswordUrlSuccessRequest"];
                    };
                };
                /** @description パラメータ誤り */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["commonErrorResponse"];
                    };
                };
                /** @description メールアドレスが登録されていない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["commonErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mail-login/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** メールアドレス認証 パスワードリセット */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description メールアドレス認証 パスワードリセット */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["postMailAuthResetPasswordRequest"];
                };
            };
            responses: {
                /** @description パスワードリセット成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description パラメータ誤り */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["commonErrorResponse"];
                    };
                };
                /** @description リセットトークン期限切れ */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["commonErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ログアウト */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ログアウト成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/withdrawal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 退会 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 退会成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description パラメータ誤り */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description すでに退会済みのユーザー */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/accessToken/valid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** アクセストークン有効チェック */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 有効 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 無効 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/accessToken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** アクセストークン取得 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description リフレッシュトークン */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["postAccessTokenSuccessRequest"];
                };
            };
            responses: {
                /** @description アクセストークン発行成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["postAccessTokenSuccessResponse"];
                    };
                };
                /** @description パラメータ誤り */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description ログインしていないのでログインし直す */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/mail-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 管理ツール用メールアドレス認証 ログイン */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 管理ツール用メールアドレス認証 ログイン */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["postAdminMailAuthLoginRequest"];
                };
            };
            responses: {
                /** @description ログイン成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["postAdminMailAuthLoginSuccessResponse"];
                    };
                };
                /** @description パラメータ誤り */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description ログイン失敗 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/accessToken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 管理ツール用アクセストークン取得 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 管理ツール用リフレッシュトークン */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["postAdminAccessTokenSuccessRequest"];
                };
            };
            responses: {
                /** @description 管理ツール用アクセストークン発行成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["postAdminAccessTokenSuccessResponse"];
                    };
                };
                /** @description パラメータ誤り */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description ログインしていないのでログインし直す */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example {
         *       "mailAddress": "user@example.com"
         *     } */
        postMailAuthTempRegistRequest: {
            /**
             * Format: email
             * @description メールアドレス
             */
            mailAddress: string;
        };
        /** @example {
         *       "registUrl": "http://localhost:7100/regist/0123456789abcdefg",
         *       "expireAt": 1735657200
         *     } */
        postMailAuthTempRegistSuccessResponse: {
            /** @description 登録用URL(local_develop環境のみ有効、それ以外の環境では空文字列が変える) */
            registUrl: string;
            /** @description 有効期限(unix time) */
            expireAt: number;
        };
        /** @example {
         *       "isValid": true,
         *       "token": "0123456789abcdef",
         *       "expireAt": 1735657200,
         *       "isFinish": false
         *     } */
        getMailAuthRegistSuccessResponse: {
            /** @description 正当なトークンか否か */
            isValid: boolean;
            /** @description メールアドレス登録用トークン */
            token: string;
            /** @description 有効期限(unix time) */
            expireAt: number;
            /** @description すでに登録済みのトークンか否か */
            isFinish: boolean;
        };
        /** @example {
         *       "password": "password_raw_string",
         *       "nickname": "username",
         *       "agreeTerm": true,
         *       "agreePrivacy": true
         *     } */
        postMailAuthRegistRequest: {
            /**
             * Format: password
             * @description パスワード(平文)
             */
            password: string;
            /** @description ユーザーネーム */
            nickname: string;
            /** @description 利用規約に同意したか否か */
            agreeTerm: boolean;
            /** @description プライバシーポリシーに同意したか否か */
            agreePrivacy: boolean;
        };
        /** @example {
         *       "userId": "0123456789abcdef",
         *       "nickname": "username",
         *       "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjF9.8lSCknTnRANlJ0AVzCgO2yF838WYA7bLaAR7vAKnofo",
         *       "accessTokenExpireAt": 1735659000,
         *       "refreshToken": "53xz5kD480ax6Oaj31TyiOpYYW2zR21tRKaX91xPk-o",
         *       "refreshTokenExpireAt": 1735743600,
         *       "isFinish": false
         *     } */
        postMailAuthRegistSuccessResponse: {
            /** @description ユーザーID */
            userId: string;
            /** @description ユーザーネーム */
            nickname: string;
            /** @description アクセストークン */
            accessToken: string;
            /** @description アクセストークンの有効期限(unix time) */
            accessTokenExpireAt: number;
            /** @description リフレッシュトークン */
            refreshToken: string;
            /** @description リフレッシュトークンの有効期限(unix time) */
            refreshTokenExpireAt: number;
            /** @description すでに登録処理済みか否か */
            isFinish: boolean;
        };
        /** @example {
         *       "message": "Hello, world!"
         *     } */
        getHelloResponse: {
            /** @description Hello, world! */
            message: string;
        };
        /** @example {
         *       "mailAddress": "user@example.com",
         *       "password": "password_raw_string"
         *     } */
        postMailAuthLoginRequest: {
            /**
             * Format: email
             * @description メールアドレス
             */
            mailAddress: string;
            /**
             * Format: password
             * @description パスワード(平文)
             */
            password: string;
        };
        /** @example {
         *       "mailAddress": "user@example.com",
         *       "password": "password_raw_string",
         *       "cpcode": "CP1234567890"
         *     } */
        postAdminMailAuthLoginRequest: {
            /**
             * Format: email
             * @description メールアドレス
             */
            mailAddress: string;
            /**
             * Format: password
             * @description パスワード
             */
            password: string;
            /** @description CPコード(付与しないと管理者としてログインを試行する) */
            cpcode?: string;
        };
        /** @example {
         *       "userId": "0123456789abcdef",
         *       "nickname": "username",
         *       "mailAddress": "user@example.com",
         *       "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjF9.8lSCknTnRANlJ0AVzCgO2yF838WYA7bLaAR7vAKnofo",
         *       "accessTokenExpireAt": 1735659000,
         *       "refreshToken": "53xz5kD480ax6Oaj31TyiOpYYW2zR21tRKaX91xPk-o",
         *       "refreshTokenExpireAt": 1735743600,
         *       "userIconId": 1,
         *       "userIconPath": "/icon/img01.png",
         *       "level": 1
         *     } */
        postMailAuthLoginSuccessResponse: {
            /** @description ユーザーID */
            userId: string;
            /** @description ユーザーネーム */
            nickname: string;
            /**
             * Format: email
             * @description メールアドレス
             */
            mailAddress: string;
            /** @description アクセストークン */
            accessToken: string;
            /** @description アクセストークンの有効期限(unix time) */
            accessTokenExpireAt: number;
            /** @description リフレッシュトークン */
            refreshToken: string;
            /** @description リフレッシュトークンの有効期限(unix time) */
            refreshTokenExpireAt: number;
            /** @description ユーザーアイコンID */
            userIconId: number;
            /** @description アイコンイメージファイルへのパス */
            userIconPath: string;
            /** @description ユーザーレベル */
            level: number;
        };
        /** @example {
         *       "currentPassword": "current_password_raw_string",
         *       "newPassword": "new_password_raw_string",
         *       "confirmNewPassword": "new_password_raw_string"
         *     } */
        postMailAuthChangePasswordRequest: {
            /**
             * Format: password
             * @description 現在のパスワード(平文)
             */
            currentPassword: string;
            /**
             * Format: password
             * @description 新しいパスワード(平文)
             */
            newPassword: string;
            /**
             * Format: password
             * @description 新しいパスワード(確認用)
             */
            confirmNewPassword: string;
        };
        /** @example {
         *       "status": 401,
         *       "reason": "パスワードが違います"
         *     } */
        postMailAuthChangePasswordErrorResponse: {
            /** @description HTTPステータスコード */
            status: number;
            /** @description 失敗理由 */
            reason: string;
        };
        /** @example {
         *       "mailAddress": "user@example.com"
         *     } */
        postMailAuthForgetPasswordUrlRequest: {
            /**
             * Format: email
             * @description 登録したメールアドレス
             */
            mailAddress: string;
        };
        /** @example {
         *       "url": "http://localhost:7000/reset-password",
         *       "expireAt": 1735657200
         *     } */
        postMailAuthForgetPasswordUrlSuccessRequest: {
            /** @description メール再発行用URL(local_develop環境のみ、他環境では空文字列が帰る) */
            url: string;
            /** @description 有効期限(unix time) */
            expireAt: number;
        };
        /** @example {
         *       "resetToken": "R2wj9WEzNaIOUnbJy9fu7M3XVmudLnxkKpg3XGW2uO4",
         *       "password": "password_raw_string",
         *       "confirmPassword": "password_raw_string"
         *     } */
        postMailAuthResetPasswordRequest: {
            /** @description パスワード再発行用トークン */
            resetToken: string;
            /**
             * Format: password
             * @description パスワード(平文)
             */
            password: string;
            /**
             * Format: password
             * @description パスワード(確認用)
             */
            confirmPassword: string;
        };
        /** @example {
         *       "refreshToken": "xOP2Zw7S_WJZx2EyrNfQjZCk92r9WNzIRO0vA0hLBNM"
         *     } */
        postAccessTokenSuccessRequest: {
            /** @description リフレッシュトークン */
            refreshToken: string;
        };
        /** @example {
         *       "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjJ9.QYdTqJ5SfsUkimZkmwxuMmWUx1tnY7szfN2g5UT0qDg",
         *       "accessTokenExpireAt": 1735659000,
         *       "refreshToken": "FIOBPYUJsIjBPVkvivgWVbXX-L69b2PhZu9t_aKRHHc",
         *       "refreshTokenExpireAt": 1735743600
         *     } */
        postAccessTokenSuccessResponse: {
            /** @description アクセストークン */
            accessToken: string;
            /** @description アクセストークンの有効期限(unix time) */
            accessTokenExpireAt: number;
            /** @description リフレッシュトークン */
            refreshToken: string;
            /** @description リフレッシュトークンの有効期限(unix time) */
            refreshTokenExpireAt: number;
        };
        /** @example {
         *       "status": 401,
         *       "reason": "パスワードが違います"
         *     } */
        commonErrorResponse: {
            /** @description HTTPステータスコード */
            status: number;
            /** @description 失敗理由 */
            reason: string;
        };
        /** @example {
         *       "userId": "user0123456789",
         *       "nickname": "username",
         *       "mailAddress": "user@example.com",
         *       "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjN9.RhmnKnohSeB_KBHmNd4zAiz7H64SiILrREPN8FkrH4Y",
         *       "accessTokenExpireAt": 1735659000,
         *       "refreshToken": "d-eaGU1Av1Lzd1FQG2vwtr0gfcM1_ojML_v0Cgt5lJQ",
         *       "refreshTokenExpireAt": 1735743600,
         *       "role": "admin"
         *     } */
        postAdminMailAuthLoginSuccessResponse: {
            /** @description ユーザーID */
            userId: string;
            /** @description ユーザーネーム */
            nickname: string;
            /**
             * Format: email
             * @description メールアドレス
             */
            mailAddress: string;
            /** @description アクセストークン */
            accessToken: string;
            /** @description アクセストークンの有効期限 */
            accessTokenExpireAt: number;
            /** @description リフレッシュトークン */
            refreshToken: string;
            /** @description リフレッシュトークンの有効期限 */
            refreshTokenExpireAt: number;
            /** @description 役割 */
            role: string;
        };
        /** @example {
         *       "refreshToken": "_yzk7cyXI2NybC2lk7pXhHowo9e7ZuQpY5mCoFyDcnU"
         *     } */
        postAdminAccessTokenSuccessRequest: {
            /** @description リフレッシュトークン */
            refreshToken: string;
        };
        /** @example {
         *       "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjN9.RhmnKnohSeB_KBHmNd4zAiz7H64SiILrREPN8FkrH4Y",
         *       "accessTokenExpireAt": 1735659000,
         *       "refreshToken": "EkiNNdrMAXD6J8gB2V69RTK1WcYxqlk0JVukm3YVlL0",
         *       "refreshTokenExpireAt": 1735743600
         *     } */
        postAdminAccessTokenSuccessResponse: {
            /** @description アクセストークン */
            accessToken: string;
            /** @description アクセストークンの有効期限 */
            accessTokenExpireAt: number;
            /** @description リフレッシュトークン */
            refreshToken: string;
            /** @description リフレッシュトークンの有効期限 */
            refreshTokenExpireAt: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
