import { MigrationInterface, QueryRunner } from "typeorm";

export class AlterTable1727761239300 implements MigrationInterface {
    name = 'AlterTable1727761239300'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`mission_tag\` DROP FOREIGN KEY \`FK_16f7de6be36936b3269ef656e2f\``);
        await queryRunner.query(`DROP INDEX \`IDX_50c21d950c94361f57a4f54a55\` ON \`mission_tag\``);
        await queryRunner.query(`ALTER TABLE \`mission_tag\` DROP COLUMN \`missionId\``);
        await queryRunner.query(`ALTER TABLE \`mission_tag\` ADD \`missionId\` char(38) NULL`);
        await queryRunner.query(`ALTER TABLE \`mission\` DROP FOREIGN KEY \`FK_dec57138c9e28d54eac422ba1c6\``);
        await queryRunner.query(`ALTER TABLE \`mission\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`mission\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`mission\` ADD \`id\` char(38) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`mission\` DROP COLUMN \`questId\``);
        await queryRunner.query(`ALTER TABLE \`mission\` ADD \`questId\` char(38) NULL`);
        await queryRunner.query(`ALTER TABLE \`quest_tag\` DROP FOREIGN KEY \`FK_8c65a59af970cec2644521b2f7e\``);
        await queryRunner.query(`DROP INDEX \`IDX_f1c4b029ce20f6bec83cc2f033\` ON \`quest_tag\``);
        await queryRunner.query(`ALTER TABLE \`quest_tag\` DROP COLUMN \`questId\``);
        await queryRunner.query(`ALTER TABLE \`quest_tag\` ADD \`questId\` char(38) NULL`);
        await queryRunner.query(`ALTER TABLE \`category_quest\` DROP FOREIGN KEY \`FK_b39a629aaa45b77eab51e814e91\``);
        await queryRunner.query(`ALTER TABLE \`quest\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`quest\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`quest\` ADD \`id\` char(38) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`category_quest\` DROP FOREIGN KEY \`FK_9cd3dfaa3e2a948c64677e2e7c5\``);
        await queryRunner.query(`DROP INDEX \`IDX_992f9fd26eea80786798703154\` ON \`category_quest\``);
        await queryRunner.query(`ALTER TABLE \`category_quest\` DROP COLUMN \`categoryId\``);
        await queryRunner.query(`ALTER TABLE \`category_quest\` ADD \`categoryId\` char(38) NULL`);
        await queryRunner.query(`ALTER TABLE \`category_quest\` DROP COLUMN \`questId\``);
        await queryRunner.query(`ALTER TABLE \`category_quest\` ADD \`questId\` char(38) NULL`);
        await queryRunner.query(`ALTER TABLE \`category_tag\` DROP FOREIGN KEY \`FK_4c2621b90d12c22fba97f1e4686\``);
        await queryRunner.query(`DROP INDEX \`IDX_fa027a64cd787b2a96880bf48b\` ON \`category_tag\``);
        await queryRunner.query(`ALTER TABLE \`category_tag\` DROP COLUMN \`categoryId\``);
        await queryRunner.query(`ALTER TABLE \`category_tag\` ADD \`categoryId\` char(38) NULL`);
        await queryRunner.query(`ALTER TABLE \`genre_category\` DROP FOREIGN KEY \`FK_b885d3161ab1cc5b76e89a8a33d\``);
        await queryRunner.query(`ALTER TABLE \`category\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`category\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`category\` ADD \`id\` char(38) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`genre_category\` DROP FOREIGN KEY \`FK_9e52611cbb39d120b0d7bf57396\``);
        await queryRunner.query(`DROP INDEX \`IDX_c2e8ad82d166e5eb29cc964ffa\` ON \`genre_category\``);
        await queryRunner.query(`ALTER TABLE \`genre_category\` DROP COLUMN \`genreId\``);
        await queryRunner.query(`ALTER TABLE \`genre_category\` ADD \`genreId\` char(38) NULL`);
        await queryRunner.query(`ALTER TABLE \`genre_category\` DROP COLUMN \`categoryId\``);
        await queryRunner.query(`ALTER TABLE \`genre_category\` ADD \`categoryId\` char(38) NULL`);
        await queryRunner.query(`ALTER TABLE \`genre_tag\` DROP FOREIGN KEY \`FK_500d84b2eaa076f2728449f0102\``);
        await queryRunner.query(`ALTER TABLE \`genre\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`genre\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`genre\` ADD \`id\` char(38) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`DROP INDEX \`IDX_58fca4f90f52942af17df70fb8\` ON \`genre_tag\``);
        await queryRunner.query(`ALTER TABLE \`genre_tag\` DROP COLUMN \`genreId\``);
        await queryRunner.query(`ALTER TABLE \`genre_tag\` ADD \`genreId\` char(38) NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_50c21d950c94361f57a4f54a55\` ON \`mission_tag\` (\`missionId\`, \`tagId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_f1c4b029ce20f6bec83cc2f033\` ON \`quest_tag\` (\`questId\`, \`tagId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_992f9fd26eea80786798703154\` ON \`category_quest\` (\`categoryId\`, \`questId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_fa027a64cd787b2a96880bf48b\` ON \`category_tag\` (\`categoryId\`, \`tagId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_c2e8ad82d166e5eb29cc964ffa\` ON \`genre_category\` (\`genreId\`, \`categoryId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_58fca4f90f52942af17df70fb8\` ON \`genre_tag\` (\`genreId\`, \`tagId\`)`);
        await queryRunner.query(`ALTER TABLE \`mission_tag\` ADD CONSTRAINT \`FK_16f7de6be36936b3269ef656e2f\` FOREIGN KEY (\`missionId\`) REFERENCES \`mission\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mission\` ADD CONSTRAINT \`FK_dec57138c9e28d54eac422ba1c6\` FOREIGN KEY (\`questId\`) REFERENCES \`quest\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`quest_tag\` ADD CONSTRAINT \`FK_8c65a59af970cec2644521b2f7e\` FOREIGN KEY (\`questId\`) REFERENCES \`quest\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`category_quest\` ADD CONSTRAINT \`FK_9cd3dfaa3e2a948c64677e2e7c5\` FOREIGN KEY (\`categoryId\`) REFERENCES \`category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`category_quest\` ADD CONSTRAINT \`FK_b39a629aaa45b77eab51e814e91\` FOREIGN KEY (\`questId\`) REFERENCES \`quest\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`category_tag\` ADD CONSTRAINT \`FK_4c2621b90d12c22fba97f1e4686\` FOREIGN KEY (\`categoryId\`) REFERENCES \`category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`genre_category\` ADD CONSTRAINT \`FK_9e52611cbb39d120b0d7bf57396\` FOREIGN KEY (\`genreId\`) REFERENCES \`genre\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`genre_category\` ADD CONSTRAINT \`FK_b885d3161ab1cc5b76e89a8a33d\` FOREIGN KEY (\`categoryId\`) REFERENCES \`category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`genre_tag\` ADD CONSTRAINT \`FK_500d84b2eaa076f2728449f0102\` FOREIGN KEY (\`genreId\`) REFERENCES \`genre\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`genre_tag\` DROP FOREIGN KEY \`FK_500d84b2eaa076f2728449f0102\``);
        await queryRunner.query(`ALTER TABLE \`genre_category\` DROP FOREIGN KEY \`FK_b885d3161ab1cc5b76e89a8a33d\``);
        await queryRunner.query(`ALTER TABLE \`genre_category\` DROP FOREIGN KEY \`FK_9e52611cbb39d120b0d7bf57396\``);
        await queryRunner.query(`ALTER TABLE \`category_tag\` DROP FOREIGN KEY \`FK_4c2621b90d12c22fba97f1e4686\``);
        await queryRunner.query(`ALTER TABLE \`category_quest\` DROP FOREIGN KEY \`FK_b39a629aaa45b77eab51e814e91\``);
        await queryRunner.query(`ALTER TABLE \`category_quest\` DROP FOREIGN KEY \`FK_9cd3dfaa3e2a948c64677e2e7c5\``);
        await queryRunner.query(`ALTER TABLE \`quest_tag\` DROP FOREIGN KEY \`FK_8c65a59af970cec2644521b2f7e\``);
        await queryRunner.query(`ALTER TABLE \`mission\` DROP FOREIGN KEY \`FK_dec57138c9e28d54eac422ba1c6\``);
        await queryRunner.query(`ALTER TABLE \`mission_tag\` DROP FOREIGN KEY \`FK_16f7de6be36936b3269ef656e2f\``);
        await queryRunner.query(`DROP INDEX \`IDX_58fca4f90f52942af17df70fb8\` ON \`genre_tag\``);
        await queryRunner.query(`DROP INDEX \`IDX_c2e8ad82d166e5eb29cc964ffa\` ON \`genre_category\``);
        await queryRunner.query(`DROP INDEX \`IDX_fa027a64cd787b2a96880bf48b\` ON \`category_tag\``);
        await queryRunner.query(`DROP INDEX \`IDX_992f9fd26eea80786798703154\` ON \`category_quest\``);
        await queryRunner.query(`DROP INDEX \`IDX_f1c4b029ce20f6bec83cc2f033\` ON \`quest_tag\``);
        await queryRunner.query(`DROP INDEX \`IDX_50c21d950c94361f57a4f54a55\` ON \`mission_tag\``);
        await queryRunner.query(`ALTER TABLE \`genre_tag\` DROP COLUMN \`genreId\``);
        await queryRunner.query(`ALTER TABLE \`genre_tag\` ADD \`genreId\` varchar(36) NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_58fca4f90f52942af17df70fb8\` ON \`genre_tag\` (\`genreId\`, \`tagId\`)`);
        await queryRunner.query(`ALTER TABLE \`genre\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`genre\` ADD \`id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`genre\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`genre_tag\` ADD CONSTRAINT \`FK_500d84b2eaa076f2728449f0102\` FOREIGN KEY (\`genreId\`) REFERENCES \`genre\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`genre_category\` DROP COLUMN \`categoryId\``);
        await queryRunner.query(`ALTER TABLE \`genre_category\` ADD \`categoryId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`genre_category\` DROP COLUMN \`genreId\``);
        await queryRunner.query(`ALTER TABLE \`genre_category\` ADD \`genreId\` varchar(36) NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_c2e8ad82d166e5eb29cc964ffa\` ON \`genre_category\` (\`genreId\`, \`categoryId\`)`);
        await queryRunner.query(`ALTER TABLE \`genre_category\` ADD CONSTRAINT \`FK_9e52611cbb39d120b0d7bf57396\` FOREIGN KEY (\`genreId\`) REFERENCES \`genre\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`category\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`category\` ADD \`id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`category\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`genre_category\` ADD CONSTRAINT \`FK_b885d3161ab1cc5b76e89a8a33d\` FOREIGN KEY (\`categoryId\`) REFERENCES \`category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`category_tag\` DROP COLUMN \`categoryId\``);
        await queryRunner.query(`ALTER TABLE \`category_tag\` ADD \`categoryId\` varchar(36) NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_fa027a64cd787b2a96880bf48b\` ON \`category_tag\` (\`categoryId\`, \`tagId\`)`);
        await queryRunner.query(`ALTER TABLE \`category_tag\` ADD CONSTRAINT \`FK_4c2621b90d12c22fba97f1e4686\` FOREIGN KEY (\`categoryId\`) REFERENCES \`category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`category_quest\` DROP COLUMN \`questId\``);
        await queryRunner.query(`ALTER TABLE \`category_quest\` ADD \`questId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`category_quest\` DROP COLUMN \`categoryId\``);
        await queryRunner.query(`ALTER TABLE \`category_quest\` ADD \`categoryId\` varchar(36) NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_992f9fd26eea80786798703154\` ON \`category_quest\` (\`categoryId\`, \`questId\`)`);
        await queryRunner.query(`ALTER TABLE \`category_quest\` ADD CONSTRAINT \`FK_9cd3dfaa3e2a948c64677e2e7c5\` FOREIGN KEY (\`categoryId\`) REFERENCES \`category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`quest\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`quest\` ADD \`id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`quest\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`category_quest\` ADD CONSTRAINT \`FK_b39a629aaa45b77eab51e814e91\` FOREIGN KEY (\`questId\`) REFERENCES \`quest\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`quest_tag\` DROP COLUMN \`questId\``);
        await queryRunner.query(`ALTER TABLE \`quest_tag\` ADD \`questId\` varchar(36) NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_f1c4b029ce20f6bec83cc2f033\` ON \`quest_tag\` (\`questId\`, \`tagId\`)`);
        await queryRunner.query(`ALTER TABLE \`quest_tag\` ADD CONSTRAINT \`FK_8c65a59af970cec2644521b2f7e\` FOREIGN KEY (\`questId\`) REFERENCES \`quest\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mission\` DROP COLUMN \`questId\``);
        await queryRunner.query(`ALTER TABLE \`mission\` ADD \`questId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`mission\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`mission\` ADD \`id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`mission\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`mission\` ADD CONSTRAINT \`FK_dec57138c9e28d54eac422ba1c6\` FOREIGN KEY (\`questId\`) REFERENCES \`quest\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mission_tag\` DROP COLUMN \`missionId\``);
        await queryRunner.query(`ALTER TABLE \`mission_tag\` ADD \`missionId\` varchar(36) NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_50c21d950c94361f57a4f54a55\` ON \`mission_tag\` (\`missionId\`, \`tagId\`)`);
        await queryRunner.query(`ALTER TABLE \`mission_tag\` ADD CONSTRAINT \`FK_16f7de6be36936b3269ef656e2f\` FOREIGN KEY (\`missionId\`) REFERENCES \`mission\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
