/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/hello": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hello world */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Hello world */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["getHelloResponse"];
                    };
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruit-company": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 求人企業リスト取得 */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description ソート順指定
                     * @example -id
                     */
                    sort?: string;
                    /**
                     * @description 取得上限指定
                     * @example 50
                     */
                    limit?: number;
                    /**
                     * @description オフセット指定
                     * @example 0
                     */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 求人企業リスト */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 求人企業リスト */
                            recruitCompanies: components["schemas"]["getRecruitCompanyListResponse"][];
                            /**
                             * @description 総求人企業数
                             * @example 100
                             */
                            total: number;
                        };
                    };
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** 求人企業新規追加 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 新規追加求人企業情報 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["postNewRecruitCompanyRequest"];
                };
            };
            responses: {
                /** @description 新規追加成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description リクエストデータがおかしい */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 権限がない */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruit-company/{recruitCompanyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 求人企業詳細取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description 求人企業ID
                     * @example 1234567890
                     */
                    recruitCompanyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 求人企業詳細 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["getRecruitCompanyDetailRequest"];
                    };
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 存在しない企業 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** 求人企業情報更新 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description 求人企業ID
                     * @example 1234567890
                     */
                    recruitCompanyId: string;
                };
                cookie?: never;
            };
            /** @description 更新求人企業情報 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["putRecruitCompanyRequest"];
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["putRecruitCompanyResponse"];
                    };
                };
                /** @description リクエストデータがおかしい */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 権限がない */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 存在しない企業 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** 求人企業削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description 求人企業ID
                     * @example 1234567890
                     */
                    recruitCompanyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 権限がない */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 存在しない企業 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/company-type": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 企業種別リスト取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 企業種別リスト */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 企業種別リスト */
                            companyTypes: components["schemas"]["oneCompanyType"][];
                        };
                    };
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wanted-ads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 求人広告リスト取得 */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description ソート順指定
                     * @example -id
                     */
                    sort?: string;
                    /**
                     * @description 取得上限指定
                     * @example 50
                     */
                    limit?: number;
                    /**
                     * @description オフセット指定
                     * @example 0
                     */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 求人広告リスト */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 求人広告リスト */
                            wantedAds: components["schemas"]["getRecruitCompanyWantedAdsListResponse"][];
                            /**
                             * @description 総求人広告数
                             * @example 100
                             */
                            total: number;
                        };
                    };
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** 求人広告新規作成 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 求人広告新規作成 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["postNewRecruitCompanyWantedAdsRequest"];
                };
            };
            responses: {
                /** @description 新規追加成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description リクエストデータがおかしい */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 権限がない */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wanted-ads/{wantedAdsId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 求人広告詳細取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description 求人広告ID
                     * @example 1234567890
                     */
                    wantedAdsId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 求人広告詳細 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["getRecruitCompanyWantedAdsDetailResponse"];
                    };
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** 求人広告更新 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description 求人広告ID
                     * @example 1234567890
                     */
                    wantedAdsId: string;
                };
                cookie?: never;
            };
            /** @description 求人広告更新 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["putRecruitCompanyWantedAds"];
                };
            };
            responses: {
                /** @description 求人広告更新成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 存在しない求人広告 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** 求人広告削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description 求人広告ID
                     * @example 1234567890
                     */
                    wantedAdsId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 求人広告削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 存在しない求人広告 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/official-news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 公式ニュースリスト取得 */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description ソート順指定
                     * @example -id
                     */
                    sort?: string;
                    /**
                     * @description 取得上限指定
                     * @example 50
                     */
                    limit?: number;
                    /**
                     * @description オフセット指定
                     * @example 0
                     */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 公式ニュースリスト */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 公式ニュースリスト */
                            news: components["schemas"]["oneOfficialNewsSummary"][];
                            /**
                             * @description 総公式ニュース数
                             * @example 100
                             */
                            total: number;
                        };
                    };
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** 公式ニュース新規作成 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 公式ニュース新規作成 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["postNewOfficialNewsResponse"];
                };
            };
            responses: {
                /** @description 新規追加成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description リクエストデータがおかしい */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 権限がない */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/official-news/{officialNewsId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 公式ニュース詳細取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description 公式ニュースID
                     * @example 1234567890
                     */
                    officialNewsId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 公式ニュース詳細 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["getOfficialNewsDetailResponse"];
                    };
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** 公式ニュース更新 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description 公式ニュースID
                     * @example 1234567890
                     */
                    officialNewsId: string;
                };
                cookie?: never;
            };
            /** @description 公式ニュース更新 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["putUpdateOfficialNewsRequest"];
                };
            };
            responses: {
                /** @description 公式ニュース更新成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** 公式ニュース削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description 公式ニュースID
                     * @example 1234567890
                     */
                    officialNewsId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 公式ニュース削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruit-company/user/{recruitCompanyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 求人企業ユーザーリスト取得 */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description ソート順指定
                     * @example -id
                     */
                    sort?: string;
                    /**
                     * @description 取得上限指定
                     * @example 50
                     */
                    limit?: number;
                    /**
                     * @description オフセット指定
                     * @example 0
                     */
                    offset?: number;
                };
                header?: never;
                path: {
                    /**
                     * @description 求人企業ID
                     * @example 1
                     */
                    recruitCompanyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 求人企業ユーザーリスト */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 企業ユーザーリスト */
                            users: components["schemas"]["oneRecruitCompanyUser"][];
                            /**
                             * @description 企業ユーザー総数
                             * @example 50
                             */
                            total: number;
                        };
                    };
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 権限がない */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 企業が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** 求人企業ユーザー追加 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 追加求人企業ユーザー */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["postRecruitCompanyUserRequest"];
                };
            };
            responses: {
                /** @description ユーザー追加成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 権限がない */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description ユーザーか企業が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** 求人企業ユーザー削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 削除求人企業ユーザー */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["deleteRecruitCompanyUserRequest"];
                };
            };
            responses: {
                /** @description ユーザー削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 権限がない */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description ユーザーか企業が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruit-company/{recruitCompanyId}/receive-apply-job-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 求人企業求人応募受取ユーザー取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description 求人企業ID
                     * @example 1
                     */
                    recruitCompanyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 求人企業求人応募受取ユーザー */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["oneRecruitCompanyUser"];
                    };
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 権限がない */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 担当者が登録されていない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** 求人企業求人応募受取ユーザー変更 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description 求人企業ID
                     * @example 1
                     */
                    recruitCompanyId: string;
                };
                cookie?: never;
            };
            /** @description 変更先ユーザー */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["putRecruitCompanyReceiveApplyJobUser"];
                };
            };
            responses: {
                /** @description ユーザー変更成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 権限がない */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description ユーザーか企業が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/user/me/message-room": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** メッセージルーム情報取得 */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description ソート順指定
                     * @example -id
                     */
                    sort?: string;
                    /**
                     * @description 取得上限指定
                     * @example 50
                     */
                    limit?: number;
                    /**
                     * @description オフセット指定
                     * @example 0
                     */
                    offset?: number;
                    /** @description 1で非表示のルームも含める。デフォルトは含めない */
                    includeCloseRoom?: number;
                    /** @description 1での未読ポストがあるもののみ取得。デフォルトは無効 */
                    newPostOnly?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description メッセージルール情報のリスト */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["getMessageRoomList"];
                    };
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/user/me/message-room/{messageRoomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** メッセージルーム情報を取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description メッセージルームID
                     * @example sbUrXP0zI6x4_bwXYMVPOEuW7O7pO5VDGcLePoPp0tY
                     */
                    messageRoomId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description メッセージルーム情報 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["oneMessageRoom"];
                    };
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 自分は参加していなメッセージルームが指定された */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 存在しないメッセージルーム */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** メッセージルームを非表示にする */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description メッセージルームID
                     * @example sbUrXP0zI6x4_bwXYMVPOEuW7O7pO5VDGcLePoPp0tY
                     */
                    messageRoomId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 非表示化成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 自分は参加していなメッセージルームが指定された */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 存在しないメッセージルーム */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/user/me/message-room/{messageRoomId}/post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** メッセージルームポスト取得 */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description ソート順指定
                     * @example -id
                     */
                    sort?: string;
                    /**
                     * @description 取得上限指定
                     * @example 50
                     */
                    limit?: number;
                    /**
                     * @description オフセット指定
                     * @example 0
                     */
                    offset?: number;
                };
                header?: never;
                path: {
                    /**
                     * @description メッセージルームID
                     * @example ck69Il_FWmJnUvWCyL5Ck8eC7mTU8bCqRoAyt3cRXvc
                     */
                    messageRoomId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description メッセージルームポストリスト */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["getMessageRoomPostList"];
                    };
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 自分は参加していなメッセージルームが指定された */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description メッセージルームが存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** メッセージルームにポストを送信する */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description メッセージルームID
                     * @example ck69Il_FWmJnUvWCyL5Ck8eC7mTU8bCqRoAyt3cRXvc
                     */
                    messageRoomId: string;
                };
                cookie?: never;
            };
            /** @description ポスト内容 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["postMessageRoomPostRequest"];
                };
            };
            responses: {
                /** @description ポスト送信完了 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 内容に不備がある */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["postMessageRoomPostFailResponse"];
                    };
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 自分が所属していないメッセージルームが指定された */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 存在しない求人広告 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/apply-for-job/message-room/readonly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** メッセージルーム情報取得(readonly) */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description ソート順指定
                     * @example -id
                     */
                    sort?: string;
                    /**
                     * @description 取得上限指定
                     * @example 50
                     */
                    limit?: number;
                    /**
                     * @description オフセット指定
                     * @example 0
                     */
                    offset?: number;
                    /** @description 1で非表示のルームも含める。デフォルトは含めない */
                    includeCloseRoom?: number;
                    /** @description 1での未読ポストがあるもののみ取得。デフォルトは無効 */
                    newPostOnly?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description メッセージルール情報のリスト */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["getMessageRoomList"];
                    };
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 権限がない */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/apply-for-job/message-room/{messageRoomId}/readonly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** メッセージルーム情報を取得する(readonly) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description メッセージルームID
                     * @example sbUrXP0zI6x4_bwXYMVPOEuW7O7pO5VDGcLePoPp0tY
                     */
                    messageRoomId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description メッセージルーム情報 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["oneMessageRoom"];
                    };
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 権限がない */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 存在しないメッセージルーム */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/apply-for-job/message-room/{messageRoomId}/post/readonly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** メッセージルームポスト取得(readonly) */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description ソート順指定
                     * @example -id
                     */
                    sort?: string;
                    /**
                     * @description 取得上限指定
                     * @example 50
                     */
                    limit?: number;
                    /**
                     * @description オフセット指定
                     * @example 0
                     */
                    offset?: number;
                };
                header?: never;
                path: {
                    /**
                     * @description メッセージルームID
                     * @example ck69Il_FWmJnUvWCyL5Ck8eC7mTU8bCqRoAyt3cRXvc
                     */
                    messageRoomId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description メッセージルームポストリスト */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["getMessageRoomPostList"];
                    };
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 権限がない */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description メッセージルームが存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/user/me/message-room/{messageRoomId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** メッセージルームの求人ステータスを変更する */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description メッセージルームID
                     * @example ck69Il_FWmJnUvWCyL5Ck8eC7mTU8bCqRoAyt3cRXvc
                     */
                    messageRoomId: string;
                };
                cookie?: never;
            };
            /** @description ポスト内容 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["putMessageRoomApplyJobStatusRequest"];
                };
            };
            responses: {
                /** @description 変更完了 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 内容に不備がある */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["postMessageRoomPostFailResponse"];
                    };
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 自分が所属していないメッセージルームが指定された */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 存在しない求人広告 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/offer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ユーザーにオファーを出す */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description オファー内容 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["putOfferFromRecruitCompanyRequest"];
                };
            };
            responses: {
                /** @description オファー完了 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 内容に不備がある */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["commonSimpleErrorResponse"];
                    };
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 存在しないユーザー */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/my-recruit-company": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自求人企業詳細取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 自求人企業詳細 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["getRecruitCompanyDetailRequest"];
                    };
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 存在しない企業 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** 自求人企業情報更新 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 自更新求人企業情報 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["putRecruitCompanyRequest"];
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["putRecruitCompanyResponse"];
                    };
                };
                /** @description リクエストデータがおかしい */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 権限がない */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 存在しない企業 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/my-recruit-company/wanted-ads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自社求人広告リスト取得 */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description ソート順指定
                     * @example -id
                     */
                    sort?: string;
                    /**
                     * @description 取得上限指定
                     * @example 50
                     */
                    limit?: number;
                    /**
                     * @description オフセット指定
                     * @example 0
                     */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 自社求人広告リスト */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 自社求人広告リスト */
                            wantedAds: components["schemas"]["getRecruitCompanyWantedAdsListResponse"][];
                            /**
                             * @description 総自社求人広告数
                             * @example 100
                             */
                            total: number;
                        };
                    };
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** 自社求人広告新規作成 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 自社求人広告新規作成 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["postNewMyRecruitCompanyWantedAdsRequest"];
                };
            };
            responses: {
                /** @description 新規追加成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description リクエストデータがおかしい */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 権限がない */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/my-recruit-company/wanted-ads/{wantedAdsId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自社求人広告詳細取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description 求人広告ID
                     * @example 1234567890
                     */
                    wantedAdsId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 自社求人広告詳細 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["getRecruitCompanyWantedAdsDetailResponse"];
                    };
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** 自社求人広告更新 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description 求人広告ID
                     * @example 1234567890
                     */
                    wantedAdsId: string;
                };
                cookie?: never;
            };
            /** @description 自社求人広告更新 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["putMyRecruitCompanyWantedAdsRequest"];
                };
            };
            responses: {
                /** @description 求人広告更新成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 存在しない求人広告 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** 自社求人広告削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description 求人広告ID
                     * @example 1234567890
                     */
                    wantedAdsId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 求人広告削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description アクセストークン期限切れ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 存在しない求人広告 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example {
         *       "title": "求人広告タイトル",
         *       "position": "募集職種",
         *       "workLocation": "勤務地",
         *       "employmentStatus": "雇用形態",
         *       "numberOfPeople": "募集人数",
         *       "details": "仕事内容の詳細",
         *       "requirements": "応募条件",
         *       "salaryAndBenefits": "給与・待遇",
         *       "officeHour": "勤務時間",
         *       "dayOff": "休日・休暇",
         *       "welfareProgram": "福利厚生",
         *       "howToApply": "応募方法",
         *       "applicationDocuments": "応募書類",
         *       "applicationDeadline": "2026-01-01",
         *       "beginAt": "2025-01-01",
         *       "endAt": "2026-01-01"
         *     } */
        putMyRecruitCompanyWantedAdsRequest: {
            /** @description 求人広告タイトル */
            title: string;
            /** @description 募集職種 */
            position: string;
            /** @description 勤務地 */
            workLocation: string;
            /** @description 雇用形態 */
            employmentStatus: string;
            /** @description 募集人数 */
            numberOfPeople: string;
            /** @description 仕事内容の詳細 */
            details: string;
            /** @description 応募条件 */
            requirements: string;
            /** @description 給与・待遇 */
            salaryAndBenefits: string;
            /** @description 勤務時間 */
            officeHour: string;
            /** @description 休日・休暇 */
            dayOff: string;
            /** @description 福利厚生 */
            welfareProgram: string;
            /** @description 応募方法 */
            howToApply: string;
            /** @description 応募書類 */
            applicationDocuments: string;
            /** @description 応募締切日(YYYY-MM-DD) */
            applicationDeadline: string;
            /** @description 掲載開始年月日(YYYY-MM-DD) */
            beginAt: string;
            /** @description 掲載終了年月日(YYYY-MM-DD) */
            endAt: string;
        };
        /** @example {
         *       "title": "求人広告タイトル",
         *       "position": "募集職種",
         *       "workLocation": "勤務地",
         *       "employmentStatus": "雇用形態",
         *       "numberOfPeople": "募集人数",
         *       "details": "仕事内容の詳細",
         *       "requirements": "応募条件",
         *       "salaryAndBenefits": "給与・待遇",
         *       "officeHour": "勤務時間",
         *       "dayOff": "休日・休暇",
         *       "welfareProgram": "福利厚生",
         *       "howToApply": "応募方法",
         *       "applicationDocuments": "応募書類",
         *       "applicationDeadline": "2026-01-01",
         *       "beginAt": "2025-01-01",
         *       "endAt": "2026-01-01"
         *     } */
        postNewMyRecruitCompanyWantedAdsRequest: {
            /** @description 求人広告タイトル */
            title: string;
            /** @description 募集職種 */
            position: string;
            /** @description 勤務地 */
            workLocation: string;
            /** @description 雇用形態 */
            employmentStatus: string;
            /** @description 募集人数 */
            numberOfPeople: string;
            /** @description 仕事内容の詳細 */
            details: string;
            /** @description 応募条件 */
            requirements: string;
            /** @description 給与・待遇 */
            salaryAndBenefits: string;
            /** @description 勤務時間 */
            officeHour: string;
            /** @description 休日・休暇 */
            dayOff: string;
            /** @description 福利厚生 */
            welfareProgram: string;
            /** @description 応募方法 */
            howToApply: string;
            /** @description 応募書類 */
            applicationDocuments: string;
            /** @description 応募締切日(YYYY-MM-DD) */
            applicationDeadline: string;
            /** @description 掲載開始年月日(YYYY-MM-DD) */
            beginAt: string;
            /** @description 掲載終了年月日(YYYY-MM-DD) */
            endAt: string;
        };
        commonSimpleErrorResponse: {
            reason: string;
        };
        /** @example {
         *       "userId": "1",
         *       "postBody": "メッセージ本文"
         *     } */
        putOfferFromRecruitCompanyRequest: {
            /** @description オファーしたいユーザーID */
            userId: string;
            /** @description メッセージ本文 */
            postBody: string;
        };
        /** @example {
         *       "applyJobStatus": "offerFromRecruitCompany"
         *     } */
        putMessageRoomApplyJobStatusRequest: {
            /**
             * @description 採用ステータス
             * @enum {string}
             */
            applyJobStatus: "applyJobFromUser" | "offerFromRecruitCompany" | "beforeDocumentScreening" | "documentScreening" | "beforeInterview" | "afterInterview" | "employment" | "rejection" | "cancel" | "unknown";
        };
        /** @example {
         *       "postBody": "ポストポストポスト"
         *     } */
        postMessageRoomPostRequest: {
            /** @description ポスト内容 */
            postBody: string;
        };
        postMessageRoomPostFailResponse: {
            reason: string;
        };
        /** @example {
         *       "id": "1234567890",
         *       "postUserId": "SGGkkVVQghYpnzn10D8DH6QI1XgJifPYiV9HZ4kGTMo",
         *       "postUserName": "ポストしたユーザーネーム",
         *       "postUnixTime": "1735657200",
         *       "postBody": "ポスト内容"
         *     } */
        oneMessageRoomPost: {
            /** @description ID */
            id: string;
            /** @description ポストしたユーザーID */
            postUserId: string;
            /** @description ポストしたユーザーネーム */
            postUserName: string;
            /** @description ポストした日時(unix time) */
            postUnixTime: string;
            /** @description ポスト内容 */
            postBody: string;
        };
        getMessageRoomPostList: {
            /** @description メッセージルームポストリスト */
            posts: components["schemas"]["oneMessageRoomPost"][];
            /**
             * @description 総ポスト数
             * @example 100
             */
            total: number;
        };
        /** @example {
         *       "id": "BVS2lSDjg2Vemf8AjYTTwZ0KaZgt-j5nm3s3-GikgNU",
         *       "isOwner": true,
         *       "ownerUserId": "RtG1wMd4XP8ewg9lPHPhythpjqX43uAfhU28XAwgc_Y",
         *       "ownerUserType": "user",
         *       "ownerUserName": "オーナーユーザーネーム",
         *       "invitedUserId": "9dSa8mcLq3Bvwh3itra4rnT-CjyWzclErnhZxDWM8K4",
         *       "invitedUserType": "recruitCompanyUser",
         *       "invitedUserName": "招待ユーザーネーム",
         *       "invitedRecruitCompanyId": "Niccuq6IpUpNlWtZ-IaTEdcybJL1TJ_IlvxraXRtCEk",
         *       "invitedRecruitCompanyName": "株式会社◯◯",
         *       "isClose": false,
         *       "isNewPost": true,
         *       "latestPostUnixTime": "1735657200",
         *       "latestPost": {
         *         "id": "1234567890",
         *         "postUserId": "SGGkkVVQghYpnzn10D8DH6QI1XgJifPYiV9HZ4kGTMo",
         *         "postUserName": "ポストしたユーザーネーム",
         *         "postUnixTime": "1735657200",
         *         "postBody": "ポスト内容"
         *       },
         *       "applyJobStatus": "offerFromRecruitCompany"
         *     } */
        oneMessageRoom: {
            /** @description ID */
            id: string;
            /** @description 自分がオーナーのメッセージルームか否か */
            isOwner: boolean;
            /** @description オーナーユーザーID */
            ownerUserId: string;
            /**
             * @description オーナーユーザー種別
             * @enum {string}
             */
            ownerUserType: "user" | "recruitCompanyUser";
            /** @description オーナーユーザーネーム */
            ownerUserName: string;
            /** @description オーナーユーザーが求人企業の場合、求人企業ID */
            ownerRecruitCompanyId?: string;
            /** @description オーナーユーザーが求人企業の場合、求人企業名 */
            ownerRecruitCompanyName?: string;
            /** @description 招待ユーザーID */
            invitedUserId: string;
            /**
             * @description 招待ユーザー種別
             * @enum {string}
             */
            invitedUserType: "user" | "recruitCompanyUser";
            /** @description 招待ユーザーネーム */
            invitedUserName: string;
            /** @description 招待ユーザーが求人企業の場合、求人企業ID */
            invitedRecruitCompanyId?: string;
            /** @description 招待ユーザーが求人企業の場合、求人企業名 */
            invitedRecruitCompanyName?: string;
            /** @description 非表示扱いか否か */
            isClose: boolean;
            /** @description 未読のポストがあるか否か */
            isNewPost: boolean;
            /** @description 最後のポスト投稿日時(unix time) */
            latestPostUnixTime: string;
            /** @description 最新のポスト */
            latestPost?: components["schemas"]["oneMessageRoomPost"];
            /**
             * @description 採用ステータス
             * @enum {string}
             */
            applyJobStatus: "applyJobFromUser" | "offerFromRecruitCompany" | "beforeDocumentScreening" | "documentScreening" | "beforeInterview" | "afterInterview" | "employment" | "rejection" | "cancel" | "unknown";
        };
        getMessageRoomList: {
            /** @description メッセージルームリスト */
            messageRooms: components["schemas"]["oneMessageRoom"][];
            /**
             * @description 総メッセージルームリスト数
             * @example 100
             */
            total: number;
        };
        /** @example {
         *       "userId": "1"
         *     } */
        putRecruitCompanyReceiveApplyJobUser: {
            /** @description ユーザーID */
            userId: string;
        };
        /** @example {
         *       "userId": "1",
         *       "mailAddress": "user@example.com",
         *       "isReceverApplyJobFromUser": true
         *     } */
        oneRecruitCompanyUser: {
            /** @description ユーザーID */
            userId: string;
            /**
             * Format: email
             * @description メールアドレス
             */
            mailAddress: string;
            /** @description 求人応募受取ユーザーか否か */
            isReceverApplyJobFromUser: boolean;
        };
        /** @example {
         *       "mailAddress": "user@example.com"
         *     } */
        postRecruitCompanyUserRequest: {
            /**
             * Format: email
             * @description メールアドレス
             */
            mailAddress: string;
        };
        /** @example {
         *       "mailAddress": "user@example.com"
         *     } */
        deleteRecruitCompanyUserRequest: {
            /**
             * Format: email
             * @description メールアドレス
             */
            mailAddress: string;
        };
        /** @example {
         *       "message": "Hello, world!"
         *     } */
        getHelloResponse: {
            /** @description Hello, world! */
            message: string;
        };
        /** @example {
         *       "id": "1234567890",
         *       "outgoingId": "wEfevfV0WM-op4GarAYuMEriL3BadgsgMq0KbE8hR3c",
         *       "cpcode": "CP0123456789",
         *       "name": "求人企業名称"
         *     } */
        getRecruitCompanyListResponse: {
            /** @description 求人企業ID */
            id: string;
            /** @description 求人企業ID(外部公開用) */
            outgoingId: string;
            /** @description CPコード */
            cpcode: string;
            /** @description 求人企業名称 */
            name: string;
        };
        /** @example {
         *       "name": "求人企業名称",
         *       "companyTypeId": 1,
         *       "beginPeriodAt": "2025-01-01",
         *       "endPeriodAt": "2026-01-01"
         *     } */
        postNewRecruitCompanyRequest: {
            /** @description 求人企業名称 */
            name: string;
            /** @description 企業種別ID */
            companyTypeId: number;
            /** @description 契約開始日時(YYYY-MM-DD) */
            beginPeriodAt: string;
            /** @description 契約終了日時(YYYY-MM-DD) */
            endPeriodAt: string;
        };
        /** @example {
         *       "id": "1234567890",
         *       "outgoingId": "V6Py5iIfmrxlDKy_c4W05lOtvkjcpBgSuIysWJpJTWY",
         *       "cpcode": "CP0123456789",
         *       "name": "求人企業名称",
         *       "companyTypeId": 1,
         *       "beginPeriodAt": "2025-01-01",
         *       "endPeriodAt": "2026-01-01",
         *       "displayName": "求人企業名称(表示用)",
         *       "establishmentDate": "1900-01-01",
         *       "postalCode": "123-4567",
         *       "prefectureCode": 13,
         *       "address": "求人企業住所",
         *       "phoneNumber": "0123-456-7890",
         *       "faxNumber": "0123-456-7890",
         *       "officialSiteUrl": "https://www.example.com/",
         *       "profile": "求人企業概要",
         *       "employees": "従業員数 100名",
         *       "netSales": "売上高",
         *       "contactPersonName": "採用担当者名",
         *       "contactPersonPosition": "採用担当者役職",
         *       "contactPersonPhoneNumber": "0123-456-7890",
         *       "contactPersionMailAddress": "saiyou@example.com"
         *     } */
        getRecruitCompanyDetailRequest: {
            /** @description 求人企業ID */
            id: string;
            /** @description 求人企業ID(外部公開用) */
            outgoingId: string;
            /** @description CPコード */
            cpcode: string;
            /** @description 求人企業名称 */
            name: string;
            /** @description 企業種別ID */
            companyTypeId: number;
            /** @description 契約開始日時(YYYY-MM-DD) */
            beginPeriodAt: string;
            /** @description 契約終了日時(YYYY-MM-DD) */
            endPeriodAt: string;
            /** @description 求人企業名称(表示用) */
            displayName: string;
            /** @description 設立年月日(YYYY-MM-DD) */
            establishmentDate: string;
            /** @description 郵便番号 */
            postalCode: string;
            /** @description 都道府県コード */
            prefectureCode: number;
            /** @description 住所 */
            address: string;
            /** @description 電話番号 */
            phoneNumber: string;
            /** @description FAX番号 */
            faxNumber: string;
            /** @description 公式サイトURL */
            officialSiteUrl: string;
            /** @description 企業概要 */
            profile: string;
            /** @description 従業員数 */
            employees: string;
            /** @description 売上高 */
            netSales: string;
            /** @description 担当者名 */
            contactPersonName: string;
            /** @description 担当者役職 */
            contactPersonPosition: string;
            /** @description 担当者電話番号 */
            contactPersonPhoneNumber: string;
            /** @description 担当者メールアドレス */
            contactPersionMailAddress: string;
        };
        /** @example {
         *       "id": 1,
         *       "name": "株式会社"
         *     } */
        oneCompanyType: {
            /** @description 企業種別ID */
            id: number;
            /** @description 企業種別 */
            name: string;
        };
        /** @example {
         *       "name": "求人企業名称",
         *       "companyTypeId": 1,
         *       "beginPeriodAt": "2025-01-01",
         *       "endPeriodAt": "2026-01-01",
         *       "displayName": "求人企業名称(表示用)",
         *       "establishmentDate": "1900-01-01",
         *       "postalCode": "123-4567",
         *       "prefectureCode": 13,
         *       "address": "求人企業住所",
         *       "phoneNumber": "0123-456-7890",
         *       "faxNumber": "0123-456-7890",
         *       "officialSiteUrl": "https://www.example.com/",
         *       "profile": "求人企業概要",
         *       "employees": "従業員数 100名",
         *       "netSales": "売上高",
         *       "contactPersonName": "採用担当者名",
         *       "contactPersonPosition": "採用担当者役職",
         *       "contactPersonPhoneNumber": "0123-456-7890",
         *       "contactPersionMailAddress": "saiyou@example.com"
         *     } */
        putRecruitCompanyRequest: {
            /** @description 求人企業名称 */
            name: string;
            /** @description 企業種別ID */
            companyTypeId: number;
            /** @description 契約開始年月日(YYYY-MM-DD) ※企業ユーザーは更新不可 */
            beginPeriodAt: string;
            /** @description 契約終了年月日(YYYY-MM-DD) ※企業ユーザーは更新不可 */
            endPeriodAt: string;
            /** @description 求人企業名称(表示用) */
            displayName: string;
            /** @description 設立年月日(YYYY-MM-DD) */
            establishmentDate: string;
            /** @description 郵便番号 */
            postalCode: string;
            /** @description 都道府県コード */
            prefectureCode: number;
            /** @description 住所 */
            address: string;
            /** @description 電話番号 */
            phoneNumber: string;
            /** @description FAX番号 */
            faxNumber: string;
            /** @description 公式サイトURL */
            officialSiteUrl: string;
            /** @description 企業概要 */
            profile: string;
            /** @description 従業員数 */
            employees: string;
            /** @description 売上高 */
            netSales: string;
            /** @description 担当者名 */
            contactPersonName: string;
            /** @description 担当者役職 */
            contactPersonPosition: string;
            /** @description 担当者電話番号 */
            contactPersonPhoneNumber: string;
            /** @description 担当者メールアドレス */
            contactPersionMailAddress: string;
        };
        /** @example {
         *       "id": "1234567890",
         *       "outgoingId": "V6Py5iIfmrxlDKy_c4W05lOtvkjcpBgSuIysWJpJTWY",
         *       "name": "求人企業名称",
         *       "companyTypeId": 1,
         *       "beginPeriodAt": "2025-01-01",
         *       "endPeriodAt": "2026-01-01",
         *       "displayName": "求人企業名称(表示用)",
         *       "establishmentDate": "1900-01-01",
         *       "postalCode": "123-4567",
         *       "prefectureCode": 13,
         *       "address": "求人企業住所",
         *       "phoneNumber": "0123-456-7890",
         *       "faxNumber": "0123-456-7890",
         *       "officialSiteUrl": "https://www.example.com/",
         *       "profile": "求人企業概要",
         *       "employees": "従業員数 100名",
         *       "netSales": "売上高",
         *       "contactPersonName": "採用担当者名",
         *       "contactPersonPosition": "採用担当者役職",
         *       "contactPersonPhoneNumber": "0123-456-7890",
         *       "contactPersionMailAddress": "saiyou@example.com"
         *     } */
        putRecruitCompanyResponse: {
            /** @description 求人企業ID */
            id: string;
            /** @description 求人企業ID(外部公開用) */
            outgoingId: string;
            /** @description 求人企業名称 */
            name: string;
            /** @description 企業種別ID */
            companyTypeId: number;
            /** @description 契約開始日時(YYYY-MM-DD) */
            beginPeriodAt: string;
            /** @description 契約終了日時(YYYY-MM-DD) */
            endPeriodAt: string;
            /** @description 求人企業名称(表示用) */
            displayName: string;
            /** @description 設立年月日(YYYY-MM-DD) */
            establishmentDate: string;
            /** @description 郵便番号 */
            postalCode: string;
            /** @description 都道府県コード */
            prefectureCode: number;
            /** @description 住所 */
            address: string;
            /** @description 電話番号 */
            phoneNumber: string;
            /** @description FAX番号 */
            faxNumber: string;
            /** @description 公式サイトURL */
            officialSiteUrl: string;
            /** @description 企業概要 */
            profile: string;
            /** @description 従業員数 */
            employees: string;
            /** @description 売上高 */
            netSales: string;
            /** @description 担当者名 */
            contactPersonName: string;
            /** @description 担当者役職 */
            contactPersonPosition: string;
            /** @description 担当者電話番号 */
            contactPersonPhoneNumber: string;
            /** @description 担当者メールアドレス */
            contactPersionMailAddress: string;
        };
        /** @example {
         *       "id": "1234567890",
         *       "outgoingId": "2oJ4kBKFx-iQhrwnIiC9mrGAMlypsjlNrfMRGhjso20",
         *       "companyId": "1234567890",
         *       "companyName": "求人企業名称",
         *       "title": "求人広告タイトル"
         *     } */
        getRecruitCompanyWantedAdsListResponse: {
            /** @description 求人広告ID */
            id: string;
            /** @description 求人広告ID(外部公開用) */
            outgoingId: string;
            /** @description 求人企業ID */
            companyId: string;
            /** @description 求人企業名称 */
            companyName: string;
            /** @description 求人広告タイトル */
            title: string;
        };
        /** @example {
         *       "id": "1234567890",
         *       "outgoingId": "2oJ4kBKFx-iQhrwnIiC9mrGAMlypsjlNrfMRGhjso20",
         *       "companyId": "1234567890",
         *       "companyName": "求人企業名称",
         *       "title": "求人広告タイトル",
         *       "position": "募集職種",
         *       "workLocation": "勤務地",
         *       "employmentStatus": "雇用形態",
         *       "numberOfPeople": "募集人数",
         *       "details": "仕事内容の詳細",
         *       "requirements": "応募条件",
         *       "salaryAndBenefits": "給与・待遇",
         *       "officeHour": "勤務時間",
         *       "dayOff": "休日・休暇",
         *       "welfareProgram": "福利厚生",
         *       "howToApply": "応募方法",
         *       "applicationDocuments": "応募書類",
         *       "applicationDeadline": "2026-01-01",
         *       "beginAt": "2025-01-01",
         *       "endAt": "2026-01-01"
         *     } */
        getRecruitCompanyWantedAdsDetailResponse: {
            /** @description 求人広告ID */
            id: string;
            /** @description 求人広告ID(外部公開用) */
            outgoingId: string;
            /** @description 求人企業ID */
            companyId: string;
            /** @description 求人企業名称 */
            companyName: string;
            /** @description 求人広告タイトル */
            title: string;
            /** @description 募集職種 */
            position: string;
            /** @description 勤務地 */
            workLocation: string;
            /** @description 雇用形態 */
            employmentStatus: string;
            /** @description 募集人数 */
            numberOfPeople: string;
            /** @description 仕事内容の詳細 */
            details: string;
            /** @description 応募条件 */
            requirements: string;
            /** @description 給与・待遇 */
            salaryAndBenefits: string;
            /** @description 勤務時間 */
            officeHour: string;
            /** @description 休日・休暇 */
            dayOff: string;
            /** @description 福利厚生 */
            welfareProgram: string;
            /** @description 応募方法 */
            howToApply: string;
            /** @description 応募書類 */
            applicationDocuments: string;
            /** @description 応募締切日(YYYY-MM-DD) */
            applicationDeadline: string;
            /** @description 掲載開始年月日(YYYY-MM-DD) */
            beginAt: string;
            /** @description 掲載終了年月日(YYYY-MM-DD) */
            endAt: string;
        };
        /** @example {
         *       "companyId": "1234567890",
         *       "title": "求人広告タイトル",
         *       "position": "募集職種",
         *       "workLocation": "勤務地",
         *       "employmentStatus": "雇用形態",
         *       "numberOfPeople": "募集人数",
         *       "details": "仕事内容の詳細",
         *       "requirements": "応募条件",
         *       "salaryAndBenefits": "給与・待遇",
         *       "officeHour": "勤務時間",
         *       "dayOff": "休日・休暇",
         *       "welfareProgram": "福利厚生",
         *       "howToApply": "応募方法",
         *       "applicationDocuments": "応募書類",
         *       "applicationDeadline": "2026-01-01",
         *       "beginAt": "2025-01-01",
         *       "endAt": "2026-01-01"
         *     } */
        postNewRecruitCompanyWantedAdsRequest: {
            /** @description 求人企業ID */
            companyId: string;
            /** @description 求人広告タイトル */
            title: string;
            /** @description 募集職種 */
            position: string;
            /** @description 勤務地 */
            workLocation: string;
            /** @description 雇用形態 */
            employmentStatus: string;
            /** @description 募集人数 */
            numberOfPeople: string;
            /** @description 仕事内容の詳細 */
            details: string;
            /** @description 応募条件 */
            requirements: string;
            /** @description 給与・待遇 */
            salaryAndBenefits: string;
            /** @description 勤務時間 */
            officeHour: string;
            /** @description 休日・休暇 */
            dayOff: string;
            /** @description 福利厚生 */
            welfareProgram: string;
            /** @description 応募方法 */
            howToApply: string;
            /** @description 応募書類 */
            applicationDocuments: string;
            /** @description 応募締切日(YYYY-MM-DD) */
            applicationDeadline: string;
            /** @description 掲載開始年月日(YYYY-MM-DD) */
            beginAt: string;
            /** @description 掲載終了年月日(YYYY-MM-DD) */
            endAt: string;
        };
        /** @example {
         *       "companyId": "1234567890",
         *       "title": "求人広告タイトル",
         *       "position": "募集職種",
         *       "workLocation": "勤務地",
         *       "employmentStatus": "雇用形態",
         *       "numberOfPeople": "募集人数",
         *       "details": "仕事内容の詳細",
         *       "requirements": "応募条件",
         *       "salaryAndBenefits": "給与・待遇",
         *       "officeHour": "勤務時間",
         *       "dayOff": "休日・休暇",
         *       "welfareProgram": "福利厚生",
         *       "howToApply": "応募方法",
         *       "applicationDocuments": "応募書類",
         *       "applicationDeadline": "2026-01-01",
         *       "beginAt": "2025-01-01",
         *       "endAt": "2026-01-01"
         *     } */
        putRecruitCompanyWantedAds: {
            /** @description 求人企業ID */
            companyId: string;
            /** @description 求人広告タイトル */
            title: string;
            /** @description 募集職種 */
            position: string;
            /** @description 勤務地 */
            workLocation: string;
            /** @description 雇用形態 */
            employmentStatus: string;
            /** @description 募集人数 */
            numberOfPeople: string;
            /** @description 仕事内容の詳細 */
            details: string;
            /** @description 応募条件 */
            requirements: string;
            /** @description 給与・待遇 */
            salaryAndBenefits: string;
            /** @description 勤務時間 */
            officeHour: string;
            /** @description 休日・休暇 */
            dayOff: string;
            /** @description 福利厚生 */
            welfareProgram: string;
            /** @description 応募方法 */
            howToApply: string;
            /** @description 応募書類 */
            applicationDocuments: string;
            /** @description 応募締切日(YYYY-MM-DD) */
            applicationDeadline: string;
            /** @description 掲載開始年月日(YYYY-MM-DD) */
            beginAt: string;
            /** @description 掲載終了年月日(YYYY-MM-DD) */
            endAt: string;
        };
        getOfficialNewsSummaryListResponse: {
            news: components["schemas"]["oneOfficialNewsSummary"][];
            total: number;
        };
        /** @example {
         *       "id": "1234567890",
         *       "outgoingId": "Jh7Swp04rRFFuEQh31EZ4Pqyf-JoGqfpvKubkpHRqsQ",
         *       "title": "タイトル",
         *       "priority": 10,
         *       "beginPeriodAt": "2025-01-01",
         *       "endPeriodAt": "2026-01-01",
         *       "createdAt": "2025-01-01",
         *       "updatedAt": "2025-01-02"
         *     } */
        oneOfficialNewsSummary: {
            /** @description 公式ニュースID */
            id: string;
            /** @description 公式ニュースID(外部公開用) */
            outgoingId: string;
            /** @description タイトル */
            title: string;
            /** @description 優先順位重み付け */
            priority: number;
            /** @description 掲載開始年月日(YYYY-MM-DD) */
            beginPeriodAt: string;
            /** @description 掲載終了年月日(YYYY-MM-DD) */
            endPeriodAt: string;
            /** @description 作成日時(YYYY-MM-DD) */
            createdAt: string;
            /** @description 最終更新日時(YYYY-MM-DD) */
            updatedAt: string;
        };
        /** @example {
         *       "id": "1234567890",
         *       "outgoingId": "Jh7Swp04rRFFuEQh31EZ4Pqyf-JoGqfpvKubkpHRqsQ",
         *       "title": "タイトル",
         *       "detail": "本文",
         *       "priority": 10,
         *       "beginPeriodAt": "2025-01-01",
         *       "endPeriodAt": "2026-01-01",
         *       "createdAt": "2025-01-01",
         *       "updatedAt": "2025-01-02"
         *     } */
        getOfficialNewsDetailResponse: {
            /** @description 公式ニュースID */
            id: string;
            /** @description 公式ニュースID(外部公開用) */
            outgoingId: string;
            /** @description タイトル */
            title: string;
            /** @description 本文 */
            detail: string;
            /** @description 優先順位重み付け */
            priority: number;
            /** @description 掲載開始年月日(YYYY-MM-DD) */
            beginPeriodAt: string;
            /** @description 掲載終了年月日(YYYY-MM-DD) */
            endPeriodAt: string;
            /** @description 作成年月日(YYYY-MM-DD) */
            createdAt: string;
            /** @description 最終更新年月日(YYYY-MM-DD) */
            updatedAt: string;
        };
        /** @example {
         *       "title": "タイトル",
         *       "detail": "本文",
         *       "priority": 10,
         *       "beginPeriodAt": "2025-01-01",
         *       "endPeriodAt": "2026-01-01"
         *     } */
        postNewOfficialNewsResponse: {
            /** @description タイトル */
            title: string;
            /** @description 本文 */
            detail: string;
            /** @description 優先順位重み付け */
            priority: number;
            /** @description 掲載開始年月日(YYYY-MM-DD) */
            beginPeriodAt: string;
            /** @description 掲載終了年月日(YYYY-MM-DD) */
            endPeriodAt: string;
        };
        /** @example {
         *       "title": "タイトル",
         *       "detail": "本文",
         *       "priority": 10,
         *       "beginPeriodAt": "2025-01-01",
         *       "endPeriodAt": "2026-01-01"
         *     } */
        putUpdateOfficialNewsRequest: {
            /** @description タイトル */
            title: string;
            /** @description 本文 */
            detail: string;
            /** @description 優先順位重み付け */
            priority: number;
            /** @description 掲載開始年月日(YYYY-MM-DD) */
            beginPeriodAt: string;
            /** @description 掲載終了年月日(YYYY-MM-DD) */
            endPeriodAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
